version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`

      
artifacts:
  discard-paths: yes  # yamllint disable-line rule:truthy
  files:
    - target/aws-test-app-0.0.1-SNAPSHOT.jar
    - scripts/*
    - appspec.yml
